### ISSUE TITLE
编译问题，不支持 node 0.12 和 iojs

### ISSUE THREAD

**Issue by yanxi123-com** [zoohanyoo/node-ctp#2]
我用的 centos 6.6，node 0.12，binding.gyp 里的文件路径已更新，`node-gyp rebuild` 结果如下：

```
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.3
gyp info using node@0.12.0 | linux | x64
gyp info spawn python
gyp info spawn args [ '/opt/node-v0.12.0-linux-x64/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/root/git/node-ctp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/opt/node-v0.12.0-linux-x64/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/0.12.0/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/0.12.0',
gyp info spawn args   '-Dmodule_root_dir=/root/git/node-ctp',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/root/git/node-ctp/build'
  CXX(target) Release/obj.target/shifctp/src/shifctp.o
In file included from ../src/shifctp.cc:3:
../src/wrap_trader.h:23: error: expected class-name before ‘{’ token
../src/wrap_trader.h:29: error: ISO C++ forbids declaration of ‘Arguments’ with no type
../src/wrap_trader.h:29: error: expected ‘,’ or ‘...’ before ‘&’ token
../src/wrap_trader.h:31: error: ISO C++ forbids declaration of ‘Arguments’ with no type
../src/wrap_trader.h:31: error: expected ‘,’ or ‘...’ before ‘&’ token
../src/wrap_trader.h:33: error: ISO C++ forbids declaration of ‘Arguments’ with no type
../src/wrap_trader.h:33: error: expected ‘,’ or ‘...’ before ‘&’ token
../src/wrap_trader.h:35: error: ISO C++ forbids declaration of ‘Arguments’ with no type
../src/wrap_trader.h:35: error: expected ‘,’ or ‘...’ before ‘&’ token

...

make: *** [Release/obj.target/shifctp/src/shifctp.o] Error 1
make: Leaving directory `/root/git/node-ctp/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/node-v0.12.0-linux-x64/lib/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.18.5-tinycore64
gyp ERR! command "node" "/opt/node-v0.12.0-linux-x64/bin/node-gyp" "rebuild"
gyp ERR! cwd /root/git/node-ctp
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
```

我对于 linux 编程不熟，是不是编译工具版本问题导致的问题，应该怎么去解决呢？多谢！

**Comment by yanxi123-com** [comment]
更新：换成 node 0.10.36 后，编译正常。看来是 node 版本的问题，请问有更新到 node 0.12 和 iojs 的计划么？

**Comment by zoohanyoo** [comment]
0.10和0.12在add on开发上有些区别，如果有需要用到的0.12特性的东西，会考虑升级。
昨天哥们请我吃饭，没办法给你回复，见谅！

发件人： Yanxi
发送时间： 2015-03-12 01:31
收件人： zoohanyoo/node-ctp
主题： Re: [node-ctp] 编译问题 (#2)
更新：换成 node 0.10.36 后，编译正常。看来是 node 版本的问题，请我有更新到 node 0.12 和 iojs 的计划么？

**Comment by yanxi123-com** [comment]
多谢回复，我先研究下，有问题再请教了:)

**Comment by yanxi123-com** [comment]
我希望在编写公式的工程做用到 es6 等新特性，所有想用 [nan](https://github.com/rvagg/nan) 重构下现在的 addon。周末抽空试了一下，但由于非常缺少 C++ 经验，还没有搞定。

我试着把 src/wrap_mduser.cpp 做了部分改动，diff 如下：
https://github.com/yanxi-com/node-ctp/commit/430b9f0c8854a92bce2eefca358ae9b901c741a8

node 0.10.36 下可以正常编译通过，但执行有问题， iojs-v1.5.1 下编译还有些问题。

希望有时间能帮我看看问题所在，多谢!

**Comment by ajie0112** [comment]
编译运行后，在centos7上出现coredump，gdb看堆栈显示：
Program terminated with signal 11, Segmentation fault.
#0  0x00000000008cb9b5 in OPENSSL_ia32_cpuid ()
请问各位有遇到此类问题吗？
