### ISSUE TITLE
请教win32系统上如何设置binding.gyp文件

### ISSUE THREAD

**Issue by QuantBull** [zoohanyoo/node-ctp#6]
请教win32系统上如何设置binding.gyp文件，我是c++小白，看到你的示例里是linux环境下的，在libraries里配置的文件后缀名为.so，那么在win32平台上应该如何写呢？.lib？或者.dll？望指教！

issues里有提到似乎高版本的nodejs就不支持的，我用的是最新的node5.8.0版本，该如何修改呢？希望大神也一起更新下呢。感激不尽！

另外是否方便留个qq或微信的联系方式，可以随时请教你。谢谢大神。

**Comment by QuantBull** [comment]
以下是编译时报错的部分信息：

c:\users\admin.node-gyp\5.8.0\include\node\v8.h(2968): error C2989: “v8::Array

”: 类 模板 已经声明为非类 模板 [D:\Projects\node-ctp\build\shifctp.vcxproj]
          c:\users\admin.node-gyp\5.8.0\include\node\v8.h(69) : 参见“v8::Array
”的
  声明
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3180): error C2504: “v8::Objec

t”: 未定义基类 [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3187): error C2061: 语法错误:
标识符“
FunctionCallback” [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3189): error C2059: 语法错误:“
)” [
D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3189): error C2143: 语法错误 :
缺少“
)”(在“;”的前面) [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3193): error C2061: 语法错误:
标识符“
FunctionCallback” [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3193): error C2059: 语法错误:“
)” [
D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3193): error C2143: 语法错误 :
缺少“
)”(在“;”的前面) [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3204): error C2059: 语法错误:“
retu
rn” [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3204): error C2238: 意外的标记
位于“;”
之前 [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3209): error C2146: 语法错误:
缺少“;
”(在标识符“Call”的前面) [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3215): error C2270: “GetName”
:
 非成员函数上不允许修饰符 [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3223): error C2270: “GetInferr

edName”: 非成员函数上不允许修饰符 [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3229): error C2270: “GetDispla

yName”: 非成员函数上不允许修饰符 [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3235): error C2270: “GetScript

LineNumber”: 非成员函数上不允许修饰符 [D:\Projects\node-ctp\build\shifctp.vcxpr
oj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3240): error C2270: “GetScript

ColumnNumber”: 非成员函数上不允许修饰符 [D:\Projects\node-ctp\build\shifctp.vcx
proj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3245): error C2270: “IsBuiltin

”: 非成员函数上不允许修饰符 [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3250): error C2270: “ScriptId
”
: 非成员函数上不允许修饰符 [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3256): error C2270: “GetBoundF

unction”: 非成员函数上不允许修饰符 [D:\Projects\node-ctp\build\shifctp.vcxproj]

c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3258): error C2270: “GetScript

Origin”: 非成员函数上不允许修饰符 [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3262): error C2059: 语法错误:“
priv
ate” [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3263): error C2059: 语法错误:“
)” [
D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3272): error C2504: “Object”:

未定义基类 [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3274): error C2504: “Object”:

未定义基类 [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3280): error C2143: 语法错误 :
缺少“
;”(在“<”的前面) [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3280): error C4430: 缺少类型说
明符 -
假定为 int。注意: C++ 不支持默认 int [D:\Projects\node-ctp\build\shifctp.vcxproj
]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3280): error C4430: 缺少类型说
明符 -
假定为 int。注意: C++ 不支持默认 int [D:\Projects\node-ctp\build\shifctp.vcxproj
]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3280): error C2238: 意外的标记
位于“;”
之前 [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3281): error C2143: 语法错误 :
缺少“
;”(在“<”的前面) [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3281): error C4430: 缺少类型说
明符 -
假定为 int。注意: C++ 不支持默认 int [D:\Projects\node-ctp\build\shifctp.vcxproj
]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3281): error C4430: 缺少类型说
明符 -
假定为 int。注意: C++ 不支持默认 int [D:\Projects\node-ctp\build\shifctp.vcxproj
]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3282): error C2238: 意外的标记
位于“;”
之前 [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3287): error C2143: 语法错误 :
缺少“
;”(在“<”的前面) [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3287): error C4430: 缺少类型说
明符 -
假定为 int。注意: C++ 不支持默认 int [D:\Projects\node-ctp\build\shifctp.vcxproj
]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3287): error C2238: 意外的标记
位于“;”
之前 [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3293): error C2061: 语法错误:
标识符“
Local” [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3295): error C2143: 语法错误 :
缺少“
;”(在“<”的前面) [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3295): error C4430: 缺少类型说
明符 -
假定为 int。注意: C++ 不支持默认 int [D:\Projects\node-ctp\build\shifctp.vcxproj
]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3295): error C2238: 意外的标记
位于“;”
之前 [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3297): error C2061: 语法错误:
标识符“
Local” [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3299): error C2143: 语法错误 :
缺少“
;”(在“<”的前面) [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3299): error C4430: 缺少类型说
明符 -
假定为 int。注意: C++ 不支持默认 int [D:\Projects\node-ctp\build\shifctp.vcxproj
]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3299): error C2238: 意外的标记
位于“;”
之前 [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3301): error C2061: 语法错误:
标识符“
Value” [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3305): error C2061: 语法错误:
标识符“
Value” [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3315): error C2143: 语法错误 :
缺少“
;”(在“<”的前面) [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3315): error C4430: 缺少类型说
明符 -
假定为 int。注意: C++ 不支持默认 int [D:\Projects\node-ctp\build\shifctp.vcxproj
]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3315): error C2238: 意外的标记
位于“;”
之前 [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3316): error C2143: 语法错误 :
缺少“
;”(在“<”的前面) [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3316): error C4430: 缺少类型说
明符 -
假定为 int。注意: C++ 不支持默认 int [D:\Projects\node-ctp\build\shifctp.vcxproj
]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3317): error C2238: 意外的标记
位于“;”
之前 [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3320): error C2143: 语法错误 :
缺少“
;”(在“<”的前面) [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3320): error C4430: 缺少类型说
明符 -
假定为 int。注意: C++ 不支持默认 int [D:\Projects\node-ctp\build\shifctp.vcxproj
]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3320): error C2238: 意外的标记
位于“;”
之前 [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3321): error C2143: 语法错误 :
缺少“
;”(在“<”的前面) [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3321): error C4430: 缺少类型说
明符 -
假定为 int。注意: C++ 不支持默认 int [D:\Projects\node-ctp\build\shifctp.vcxproj
]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3322): error C2238: 意外的标记
位于“;”
之前 [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3325): error C2143: 语法错误 :
缺少“
;”(在“<”的前面) [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3325): error C4430: 缺少类型说
明符 -
假定为 int。注意: C++ 不支持默认 int [D:\Projects\node-ctp\build\shifctp.vcxproj
]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3325): error C2238: 意外的标记
位于“;”
之前 [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3326): error C2143: 语法错误 :
缺少“
;”(在“<”的前面) [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3326): error C4430: 缺少类型说
明符 -
假定为 int。注意: C++ 不支持默认 int [D:\Projects\node-ctp\build\shifctp.vcxproj
]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3327): error C2238: 意外的标记
位于“;”
之前 [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3335): error C2061: 语法错误:
标识符“
Value” [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3339): error C2061: 语法错误:
标识符“
Value” [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3349): error C2332: “enum”:
缺少
标记名 [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3349): error C2236: 意外的“cla
ss”
“ArrayBufferCreationMode”。是否忘记了“;”? [D:\Projects\node-ctp\build\shifct
p.vcxproj
]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3349): error C3381: “ArrayBuff

erCreationMode”: 只有在用 /clr 选项编译的代码中才有程序集访问说明符 [D:\Project
s\node-ctp\build\shifc
tp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3349): error C4430: 缺少类型说
明符 -
假定为 int。注意: C++ 不支持默认 int [D:\Projects\node-ctp\build\shifctp.vcxproj
]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3349): error C2143: 语法错误 :
缺少“
;”(在“}”的前面) [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3349): error C4430: 缺少类型说
明符 -
假定为 int。注意: C++ 不支持默认 int [D:\Projects\node-ctp\build\shifctp.vcxproj
]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3356): error C2504: “Object”:

未定义基类 [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3373): error C2628: “ArrayBuff

er::Allocator”后面接“void”是非法的(是否忘记了“;”?) [D:\Projects\node-ctp\bu
ild\shifctp.vcxp
roj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3399): error C3861: “data_”:
找
不到标识符 [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3399): error C2461: “Contents
”
: 构造函数语法缺少形参 [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3399): error C2059: 语法错误:“
常量”
[D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3399): error C4430: 缺少类型说
明符 -
假定为 int。注意: C++ 不支持默认 int [D:\Projects\node-ctp\build\shifctp.vcxproj
]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3399): error C2143: 语法错误 :
缺少“
;”(在“{”的前面) [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3399): error C2334: “{”的前面
有意外标
记；跳过明显的函数体 [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3401): error C2059: 语法错误:“
retu
rn” [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3401): error C2238: 意外的标记
位于“;”
之前 [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3402): error C2146: 语法错误:
缺少“;
”(在标识符“ByteLength”的前面) [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3402): error C2270: “ByteLengt

h”: 非成员函数上不允许修饰符 [D:\Projects\node-ctp\build\shifctp.vcxproj]
c:\users\admin.node-gyp\5.8.0\include\node\v8.h(3402): fatal error C1003: 错误
计数
超过 100；正在停止编译 [D:\Projects\node-ctp\build\shifctp.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\admin\AppData\Roaming\npm\no
de_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:204:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\Program Files (x86)\nodejs\node.exe" "C:\Users\admin\
AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Projects\node-ctp
gyp ERR! node -v v5.8.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok

**Comment by ajie0112** [comment]
我的binding.gyp，供参考
{
    "targets":[
    {
        "target_name" : "nodectp",
        "sources": [
            "src/main.cc",
            "src/ctpmd.cc",
            "src/ctptd.cc",
        ],
        "include_dirs" : [
            "ctpv635/include/",
            "src/",
            "<!(node -e \"require('nan')\")",
        ],
        "libraries" : [
            "../ctpv635/win64/thostmduserapi.lib",
            "../ctpv635/win64/thosttraderapi.lib",  
        ],
    }
    ]
}

**Comment by QuantBull** [comment]
还是报了错，缺少文件吗？我是fork的你的node-ctp项目，按理说不该缺少文件的啊。
可以给我发一封你电脑上完整的项目不，大神。发一封给我吧，我的邮箱：383523223@qq.com
请帮忙赐教。。
以下是报错截图：
![qq 20160316173139](https://cloud.githubusercontent.com/assets/1096160/13807795/014eb5e8-eb9e-11e5-9d91-8f7034b03f02.png)

**Comment by QuantBull** [comment]
另外我的binging.gyp配置是这样的:
{
  "targets": [
    {
      "target_name": "nodectp",
      "sources": [ "src/main.cc","src/ctpmd.cc","src/ctptd.cc" ],
      "libraries":[
            "D:/Projects/node-ctp/6.3.0_20140811_traderapi_win32/thostmduserapi.lib",
            "D:/Projects/node-ctp/6.3.0_20140811_traderapi_win32/thosttraderapi.lib"
      ],
      "include_dirs":[
            "D:/Projects/node-ctp/6.3.0_20140811_traderapi_win32/include/",
            "src/",
            "<!(node -e \"require('nan')\")"
      ]
    }
  ],
}

其中include_dirs里的"D:/Projects/node-ctp/6.3.0_20140811_traderapi_win32/include/" ，我发现在6.3.0_20140811_traderapi_win32目录下并没有include文件夹，这个include文件夹应该是哪里的呢？
实在比较混乱，望指教。

**Comment by ajie0112** [comment]
sources 是我本地的项目文件列表，那个binding.gyp只是提供给你参考如何添加ctp windows lib的依赖。这个项目应该支持0.10.x 版本的Node.js, 你用5.8的变化太大了。我自己用Nan简单包装了下，也封装了一个node版本的ctp，等测试稳定后放出来吧，之前遇到linux下64位库运行coredump的问题，一直没解决。
Program terminated with signal 11, Segmentation fault.
#0 0x00000000008cb9b5 in OPENSSL_ia32_cpuid ()

**Comment by ajie0112** [comment]
include目录是我自己把ctp的头文件放进去命名的

**Comment by iamweilee** [comment]
把nodejs降级到0.10.26版本依然编译不过，是什么问题呢？
![1](https://cloud.githubusercontent.com/assets/1096160/13835913/590b60da-ec37-11e5-8f3e-f06a185f316a.png)
![2](https://cloud.githubusercontent.com/assets/1096160/13835917/5cfb3a80-ec37-11e5-98c8-054105e11e7f.png)
![3](https://cloud.githubusercontent.com/assets/1096160/13835919/601c1bf8-ec37-11e5-9109-56e70dbb2bd6.png)
![4](https://cloud.githubusercontent.com/assets/1096160/13835922/63a65f0e-ec37-11e5-91c7-b1ecdecf3acd.png)

**Comment by QuantBull** [comment]
我是win8.1 64位系统 nodejs是32位0.10.26版本 python是32位2.7.6版本 vs2010版本
环境有什么问题吗？

**Comment by QuantBull** [comment]
把nodejs降级到0.10.26版本依然编译不过，是什么问题呢？
![1](https://cloud.githubusercontent.com/assets/1096160/13842467/45a42068-ec69-11e5-8300-f5f9867c359e.png)
![2](https://cloud.githubusercontent.com/assets/1096160/13842474/537557d4-ec69-11e5-88ea-96a113ba21e4.png)
![3](https://cloud.githubusercontent.com/assets/1096160/13842481/595403a8-ec69-11e5-9cf2-8db2b7b80174.png)
![4](https://cloud.githubusercontent.com/assets/1096160/13842487/5dfc921c-ec69-11e5-8c54-3bb36d1ef6e7.png)
